public class DisplaySearch{
    
   // public boolean BankSelection{get;set;}
    public boolean name {get; set;}
    public boolean typeofLoan {get; set;}
    public boolean typeOfEmployment{get;set;}
    public boolean loanAmount {get; set;}
    public boolean standardRate {get; set;}
    public boolean rateOfOD {get; set;}
    public boolean teaserFixed {get; set;}
    public boolean baseRate {get; set;}
    public boolean processingFee {get; set;}
    public boolean frankingFees {get; set;}
    public boolean mortgageFee {get; set;}
    public boolean insurance {get; set;}
    public boolean fundingUpto {get; set;}
    public boolean preClosure {get; set;}
    public boolean ancilCharges {get; set;}
    public boolean parallelFunding {get; set;}
    public boolean adf {get; set;}
    public boolean projApproval {get; set;}
    
    public DisplaySearch(){
       // BankSelection=true;
        name= true;
        typeofLoan=true;
        typeOfEmployment=true;
        loanAmount= true;
        standardRate= true;
        rateOfOD= true;
        teaserFixed= true;
        baseRate= true;
        processingFee= true;
        frankingFees= true;
        mortgageFee= true;
        insurance= true;
        fundingUpto= true;
        preClosure= true;
        ancilCharges= true;
        parallelFunding= true;
        adf= true;
        projApproval= true;
    }
             
}